name: pizzahap
description: PizzaHap - Pizza Ordering App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # HTTP & networking
  http: ^1.2.1
  dio: ^5.4.3+1

  # State management
  provider: ^6.1.2

  # Storage
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0

  # UI
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^3.1.2
  flutter_svg: ^2.0.10+1
  badges: ^3.1.2
  smooth_page_indicator: ^1.1.0
  pinput: ^3.0.1
  fluttertoast: ^8.2.6
  loading_animation_widget: ^1.2.0+4
  fl_chart: ^0.68.0

  # Navigation
  go_router: ^13.2.4

  # FCM Push Notifications

  # Utils
  intl: ^0.20.2
  url_launcher: ^6.3.0
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  package_info_plus: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
#  assets:
#    - assets/images/
#    - assets/animations/

